FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
COPY package.json yarn.lock ./
RUN yarn install
RUN yarn build

FROM --platform=linux/arm64 jawg/nginx-spa:stable-alpine AS runner
COPY --from=builder dist/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]